# Generated by Django 4.0.5 on 2022-07-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.TimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.userdetails')),
            ],
        ),
    ]
