# Generated by Django 4.0.5 on 2022-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='passw',
            field=models.CharField(max_length=20),
        ),
    ]
