# Generated by Django 4.0.5 on 2022-07-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('passw', models.CharField(max_length=60)),
            ],
        ),
    ]
