# Generated by Django 4.0.5 on 2022-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0008_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='email',
            field=models.EmailField(default=1, max_length=85, unique=True),
            preserve_default=False,
        ),
    ]
