# Generated by Django 4.0.5 on 2022-09-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0011_rename_url_alarm_alarm_remove_alarm_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alarm',
            new_name='alarmdetail',
        ),
    ]
