# Generated by Django 4.0.5 on 2022-07-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0002_alter_trackdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdetails',
            name='email',
            field=models.EmailField(max_length=85),
        ),
    ]
