# Generated by Django 4.0.5 on 2022-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0003_alter_trackdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdetails',
            name='activetime',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='trackdetails',
            name='closetabs',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='trackdetails',
            name='opentabs',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
