# Generated by Django 4.0.5 on 2022-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0004_alter_trackdetails_activetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdetails',
            name='activetime',
            field=models.CharField(default='', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='trackdetails',
            name='closetabs',
            field=models.CharField(default='', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='trackdetails',
            name='opentabs',
            field=models.CharField(default='', max_length=800, null=True),
        ),
    ]
