# Generated by Django 4.0.5 on 2022-07-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0005_alter_trackdetails_activetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdetails',
            name='email',
            field=models.EmailField(max_length=85, unique=True),
        ),
    ]
