# Generated by Django 4.0.5 on 2022-08-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0006_alter_trackdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackdetails',
            name='activetime',
            field=models.CharField(default='', max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='trackdetails',
            name='closetabs',
            field=models.CharField(default='', max_length=60000, null=True),
        ),
        migrations.AlterField(
            model_name='trackdetails',
            name='opentabs',
            field=models.CharField(default='', max_length=60000, null=True),
        ),
    ]
