# Generated by Django 4.0.5 on 2022-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0007_alter_trackdetails_activetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=60000, null=True)),
                ('time', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
