# Generated by Django 4.0.5 on 2022-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0009_alarm_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='email',
            field=models.EmailField(max_length=85),
        ),
    ]
