# Generated by Django 4.0.5 on 2022-09-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0010_alter_alarm_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='url',
            new_name='alarm',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='time',
        ),
    ]
