# Generated by Django 4.0.5 on 2022-09-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabtracker', '0012_rename_alarm_alarmdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmdetail',
            old_name='alarm',
            new_name='alarmdet',
        ),
    ]
